### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub-Radar#12]
这里列出发布正式版需要做的功能，欢迎讨论

- [x] 设置页
  - [x] 自定义 RSSHub 域名
  - [x] 一键订阅相关：显示隐藏、Tiny Tiny RSS 域名
  - [x] 角标提醒
  - [x] 版本号 Copyright 等
- [x] 一键订阅
  - [x] Tiny Tiny RSS
  - [x] Feedly
  - [x] Inoreader
- [x] 更多的规则
- [x] ~~Changelog icon~~
